import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/application.css";

// No weight given, so next/font serves Inter as a variable font.
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={inter.variable}>
      <body>
        <div className="page">{children}</div>
      </body>
    </html>
  );
}
